export const team = [
  {
    id: 1,
    name: "Amanda Waller",
    title: "Co-Founder",
    image: "https://images.pexels.com/photos/3586798/pexels-photo-3586798.jpeg",
    socials: { twitter: "#", linkedin: "#" },
  },
  {
    id: 2,
    name: "Andrea Waller",
    title: "Director of People",
    image: "https://images.pexels.com/photos/4350098/pexels-photo-4350098.jpeg",
    socials: { twitter: "#", linkedin: "#" },
  },
  {
    id: 3,
    name: "Jerry Watson",
    title: "Head of Marketing",
    image: "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg",
    socials: { twitter: "#", linkedin: "#" },
  },
  {
    id: 4,
    name: "Sergion Tulino",
    title: "Art Director",
    image: "https://images.pexels.com/photos/3778603/pexels-photo-3778603.jpeg",
    socials: { twitter: "#", linkedin: "#" },
  },
  {
    id: 5,
    name: "Hosuh Yamada",
    title: "Designer",
    image: "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg",
    socials: { twitter: "#", linkedin: "#" },
  },
  {
    id: 6,
    name: "Bagaskara",
    title: "Sales Lead",
    image: "https://images.pexels.com/photos/2269872/pexels-photo-2269872.jpeg",
    socials: { twitter: "#", linkedin: "#" },
  },
  {
    id: 7,
    name: "Kartono Aji",
    title: "Team Lead",
    image: "https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg",
    socials: { twitter: "#", linkedin: "#" },
  },
  {
    id: 8,
    name: "Susan Fayne",
    title: "Founder",
    image: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg",
    socials: { twitter: "#", linkedin: "#" },
  },
  {
    id: 9,
    name: "Dave Gray",
    title: "CTO",
    image: "https://images.pexels.com/photos/4350098/pexels-photo-4350098.jpeg",
    socials: { twitter: "#", linkedin: "#" },
  },
];
